### ISSUE TITLE
Missing archive link

### ISSUE THREAD

**Issue by pperliti** [aldolat/posts-in-sidebar#21]
Hi,
upgrading the plugin from version 2.0.4 to version 3.0 made the link to the archive (of custom post) suddenly disappear (despite the option to show the link was checked within the widget - I also unchecked, then saved, then re-checked the option, then saved again but nothing changed).
Reverting the plugin to version 2.0.4 made the link to the archive appear as usual.

**Comment by aldolat** [comment]
Hi Paolo,
do you speak Italian?

**Comment by pperliti** [comment]
Of course I do (e meglio dell'inglese :-) 
Ho provato ad aggiornare il plugin dalla versione 2.0.4 alla versione 3.0 su un sito in produzione. Apparentemente tutto funzionava come prima, poi mi hanno segnalato che in fondo all'elenco non si vedeva più il link all'archivio notizie (si tratta di custom post). Allego file per spiegarmi meglio.
Andando a ricontrollare le opzioni del widget tutto sembrava impostato correttamente, ho provato per sicurezza a disabilitare e riabilitare l'opzione per mostrare il link all'archivio ma nulla è cambiato.
Grazie, Paolo

![postinsidebar](https://cloud.githubusercontent.com/assets/1265443/10476030/60b22cb8-724a-11e5-88da-5a694d79871b.png)

**Comment by aldolat** [comment]
> Of course I do (e meglio dell'inglese :-) 

eheheh :)

Il sistema per generare il link alla tassonomia è cambiato, al fine di dare maggiore flessibilità all'utente. Purtroppo non è compatibile con le versioni precedenti.

Se "notizie Flash" è un **custom post type**, imposta il widget così:

![custom_post_type](https://cloud.githubusercontent.com/assets/3031403/10483454/e785d228-727f-11e5-989d-aeca8628249c.png)

dove `books` è il nome del custom post type.

Se invece "notizie Flash" è una **tassonomia**, fai in questo modo:

![custom_tax](https://cloud.githubusercontent.com/assets/3031403/10483462/ecf2d9a4-727f-11e5-8724-6d5453af37f0.png)

dove `genre` è il nome della tassonomia (che corrisponde a quelle standard tipo categoria e tag) e `infotech` è il nome del termine della tassonomia (che corrisponde, ad esempio, alla voce "tecnologia" della tassonomia standard "tag").

Spero di essere stato chiaro. :)

Fammi sapere.

**Comment by pperliti** [comment]
Funziona, grazie per l'aiuto!
