### ISSUE TITLE
Widget title escaping can break use of the widget_title filter

### ISSUE THREAD

**Issue by mlang38** [aldolat/posts-in-sidebar#37]
Hello,
in the commit 1c4dfef, [the widget title has been wrapped with esc_html()](https://github.com/aldolat/posts-in-sidebar/commit/1c4dfefe62b4d1fcaed95645838d198b5fa188c9#diff-e5221c64172806a72baf77e566515913R238).
But I think (and I do it myself) that the _widget_title_ filter is often used by themes for CSS styling purposes by wrapping the title with some targetable markup. If the HTML of the title is escaped, this usage is therefore broken. I think this behavior should be reverted.

By the way, the _widget_title_ filter [is called with the instance _title_ only](https://github.com/aldolat/posts-in-sidebar/blob/1c4dfefe62b4d1fcaed95645838d198b5fa188c9/inc/class-pis-posts-in-sidebar.php#L78), but this filter [accepts more arguments](https://developer.wordpress.org/reference/hooks/widget_title/) to better target the widgets to be customized.

Anyway, thank you for this very useful plugin

**Comment by aldolat** [comment]
Hello,
you're absolutely right. Thank you for your comment. :+1: 

I made two distinct commits in `develop` branch:
* [Removed escaping in widget title](https://github.com/aldolat/posts-in-sidebar/commit/fdc18ba287d05280ae7486a323f3ff3628928ff5)
* [Added widget id when filtering the widget title](https://github.com/aldolat/posts-in-sidebar/commit/3cf44c3481d7134d0a0f47cc986ff613bf26a163)

Please, let me know if you have additional comments on this.

**Comment by mlang38** [comment]
It seems okay to me for now. Thank you very much

**Comment by aldolat** [comment]
I will release the 4.7.1 version in the upcoming days. Thank you so much for your report.
