### ISSUE TITLE
HTML validation errors

### ISSUE THREAD

**Issue by saajo-lab** [aldolat/posts-in-sidebar#41]
The following line is causing some HTML validation errors regarding pis-class

https://github.com/aldolat/posts-in-sidebar/blob/b030bd44e6c6f328966cd1d7da006df4c7f96e25/includes/pis-functions-display.php#L760

It outputs the html code like this:

`<span class="class="pis-time"">at 3:11 pm</span>`

I'm re-writing it this way to avoid validation errors:

`$post_time = ' <span ' . pis_class( 'pis-time', apply_filters( 'pis_time_class', '' ), false ) . '>' . sprintf( esc_html_x( 'at %s', '%s is the time of the post.', 'posts-in-sidebar' ), get_the_time() ) . '</span>';`

Fix for this could be great instead of manually fixing the line on every PIS update.

**Comment by aldolat** [comment]
Thank you so much! I wasn't aware of this error.
The fix is already in the [develop branch](https://github.com/aldolat/posts-in-sidebar/commit/f5a665d3381748361bfc7400e0aa415af4ce18de).

Thanks again.
