### ISSUE TITLE
Excerpt length doesn't limit as option suggests

### ISSUE THREAD

**Issue by samwood23** [aldolat/posts-in-sidebar#43]
Hi. 

I have come across an issue whereby I have selected to have the excerpt show in the output and chosen to limit the word length to 10 but it is still showing the full excerpt upon preview. I have disabled all other plugins installed to see if it is conflicting but it still seems to be happening. Any thoughts?

**Comment by aldolat** [comment]
Hi,
if a custom excerpt has been defined in the relevant panel of the post editor, it will be displayed entirely, even if the excerpt length passes the limit imposed in the plugin option.

On the contrary, a WordPress-generated excerpt will be truncated at the words/chars number defined.
