### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by danmaby** [aldolat/posts-in-sidebar#48]
Hi, I'm having an issue with the plugin. When I activated the plugin all the existing widgets in the sidebar got removed and if I add the `Post in Sidebar` block I see a number of errors. 

This is a screenshot of a WP instance with all plugins deactivated except the Post in Sidebar:

![Screenshot 2022-02-21 at 14 57 44](https://user-images.githubusercontent.com/13104185/154984238-a4d35122-ae01-4e58-a82f-1eb9725d4f84.png)

Sorry, I can't share more detail but installing, activating, and viewing the Widgets page is all I did. 

The environment: 
- WP 5.9
- Posts in Sidebar Version 4.16.3
- PHP 8.0
- mariaDB 10.4

**Comment by aldolat** [comment]
The plugin has not been ported to Gutenberg yet. You can use [Classic Widgets](https://wordpress.org/plugins/classic-widgets/) to solve the problem.
