### ISSUE TITLE
code is being displayed front end

### ISSUE THREAD

**Issue by sharon4miranda** [aldolat/posts-in-sidebar#49]
This is displayed in the sidebar 
post-option:{"post-thumbnail-style":"default","sidebar":"default-sidebar","left-sidebar":"Footer 1","right-sidebar":"Footer 1","post-rating":"none","single-banner-type":"default","single-banner-category":null,"single-banner-script":"","single-banner-max-width":"720px","single-banner-autoplay-speed":"7000","single-banner-orderby":"date","single-banner-order":"desc"}

ppma_authors_name:

**Comment by aldolat** [comment]
They're not Posts in Sidebar options. Anyway, please be advised that currently Posts in Sidebar is not compatible with Gutenberg. If you want to use this plugin, you have to use Classic Widgets plugin.
