### ISSUE TITLE
Coding Debug showing in front end

### ISSUE THREAD

**Issue by Scarlywebs** [aldolat/posts-in-sidebar#50]
Hi, thanks for the great plug-in I am new to this plug-in so don't know the total ins or outs. On my webpage front end I don't see the preview of the blog but only the Debugging information, I am not sure why.  I see fine on the backend in the widget everything displays correctly. Below is an image of what I am seeing.

![Screenshot 2022-04-24 054857](https://user-images.githubusercontent.com/104298793/164968823-dc8b2b7b-23d4-4232-b562-bd2ae3788944.jpg)
>

**Comment by aldolat** [comment]
Hi @Scarlywars,
the debug information option is activated. Deactivate it.

**Comment by Scarlywebs** [comment]
Hey, thanks for the quick reply. I tried to untick the debug information and save my changes. But for some reason when I refresh the page it shows everything tick again and refuses to save my information. I am not sure what could be causing that glitch. Below is the image of what i tried to uncheck.

![Screenshot 2022-04-24 061758](https://user-images.githubusercontent.com/104298793/164969490-9160f584-61c1-4d68-93cb-34fa8654ef8e.jpg)

**Comment by Scarlywebs** [comment]
Also just now the backend as well started showing debugged information. I am not sure what I did wrong lol.
I also just tried deleting and re-adding the widget but still kept popping up debugging issues.

**Comment by aldolat** [comment]
Untick the option and press the Save button. Perhaps did you forget to press it?

**Comment by Scarlywebs** [comment]
Oh just switched to classic widgets, didn't realize this only works with classic widgets. Well, that solves that, but now it shows don't got any posts selected. I guess I need to pick a certain category instead of all?

**Comment by aldolat** [comment]
No, you don't have to pick a category. The plugin can show, for example, last posts, without selecting a taxonomy first.

**Comment by Scarlywebs** [comment]
Alright finally got it to work had to delete my old Post Sidebar, the other one has gotten a glitch somehow. Thanks so much for your help!
