### ISSUE TITLE
Why was this plugin removed from wordpress.org?

### ISSUE THREAD

**Issue by Branden97** [aldolat/posts-in-sidebar#51]
Hi there!

I just noticed that this plugin was removed from wordpress.org 6 days ago (9/10/2022). Any idea why?
My boss is worried it might have been removed for some security vulnerability or something. I'm hoping that's not the case.

Thanks,

**Comment by aldolat** [comment]
Hi,
the plugin was closed because I have no time to maintain it anymore.
I'm very sorry for this.
Anyone that wants to continue its development is welcome.
